# Generated by Django 3.2.4 on 2021-10-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Id', models.IntegerField()),
                ('Employee_Name', models.CharField(default='Name', max_length=30)),
                ('Extrahours', models.IntegerField()),
                ('Attendance', models.CharField(max_length=50)),
                ('Clockin', models.DateTimeField()),
                ('Clockout', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Id', models.IntegerField()),
                ('Employee_Name', models.CharField(default='Name', max_length=30)),
                ('Designation', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=40)),
                ('Phone_No', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=40)),
            ],
        ),
    ]
